@WebApi.NetCore_HostAddress = http://localhost:5150

POST {{WebApi.NetCore_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "sampleuser",
  "email": "sample.user@example.com",
  "password": "StrongPass123!"
}

###
